### ISSUE TITLE
IllegalStateException at Bibliotekon.getNodeUid(Bibliotekon.java:127)

### ISSUE THREAD

**Issue by bobjacobsen** [talsma-ict/umldoclet#267] opened 2020-05-05 14:28 UTC
## Expected Behavior
Trying to create Javadoc for the [JMRI project.](https://github.com/JMRI/JMRI/) We've used the older Plantuml doclet for a long time with Java 8, but now need to work with Java 11 Javadoc.

## Actual Behavior

Many, many occurances of
```
 java.lang.IllegalStateException
  [javadoc] 	at net.sourceforge.plantuml.svek.Bibliotekon.getNodeUid(Bibliotekon.java:127)
```

## Steps to Reproduce the Problem

  1. git clone https://github.com/bobjacobsen/JMRI.git
  2. git checkout  plantUml-update
  3. ant plant-uml

## Specifications

  - Version: 2.0.9 (released Jar file)
  - Platform: macOS Mojave
  - Java version: 11
  - Project link: https://github.com/JMRI/JMRI/
(but the recreating-branch is in https://github.com/bobjacobsen/JMRI )

Traceback:

```
  [javadoc] java.lang.IllegalStateException
  [javadoc] 	at net.sourceforge.plantuml.svek.Bibliotekon.getNodeUid(Bibliotekon.java:127)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.Link.getEntityPort1(Link.java:251)
  [javadoc] 	at net.sourceforge.plantuml.svek.Line.<init>(Line.java:227)
  [javadoc] 	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:373)
  [javadoc] 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:102)
  [javadoc] 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:646)
  [javadoc] 	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:188)
  [javadoc] 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
  [javadoc] 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
  [javadoc] 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:153)
  [javadoc] 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:125)
  [javadoc] 	at nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:172)
  [javadoc] 	at nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:132)
  [javadoc] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
  [javadoc] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  [javadoc] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
  [javadoc] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  [javadoc] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  [javadoc] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  [javadoc] 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
  [javadoc] 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
  [javadoc] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
  [javadoc] 	at nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)

```

**Comment by sjoerdtalsma** [comment] 2020-05-05 14:50
First of all thank you for reporting this and providing a replicating github branch. That will make reproducing the bug much easier.

**Comment by sjoerdtalsma** [comment] 2020-05-05 15:47
Hmmm, at first glance this looks like it could be a bug in a recent plantuml library version.
Also, I _do_ get some diagrams generated even though exceptions were thrown for these .. 🤔 

I will try generating with an earlier plantuml version.

**Comment by bobjacobsen** [comment] 2020-05-05 17:34
Yes, it does seem to be generating diagrams, which is _excellent_!  Thank you for this.

At the end, it produced a set of additional messages:
```
 [javadoc] java.lang.IllegalStateException: Timeout4 TIMEOUT
  [javadoc] 	at net.sourceforge.plantuml.svek.DotStringFactory.getSvg(DotStringFactory.java:303)
  [javadoc] 	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:407)
  [javadoc] 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:102)
  [javadoc] 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:646)
  [javadoc] 	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:188)
  [javadoc] 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
  [javadoc] 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
  [javadoc] 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:153)
  [javadoc] 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:125)
  [javadoc] 	at nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:172)
  [javadoc] 	at nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:132)
  [javadoc] 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
  [javadoc] 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
  [javadoc] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
  [javadoc] 	at nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
  [javadoc] TimeoutExecutorB java.lang.InterruptedException
  [javadoc] java.lang.InterruptedException
  [javadoc] 	at java.base/java.lang.Object.wait(Native Method)
  [javadoc] 	at java.base/java.lang.Object.wait(Object.java:328)
  [javadoc] 	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.joinInternal(ProcessRunner.java:197)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:120)
  [javadoc] 	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:74)
```
but it does seem to have generated a complete set.

**Comment by bobjacobsen** [comment] 2020-05-06 15:34
The Javadoc that's being produced seems good _except_ the main packages page, which displaying the error shown below.  I'm adding it here in case it's useful information.

We're using umldoclet on a pretty big project. Is there a way to increase the length of that timeout?

Thanks again for this, it's producing lots of really useful info.

```
An error has occured : java.lang.IllegalStateException: Timeout4 TIMEOUT
A robot may not injure a human being or, through inaction, allow a human being to come to harm.
Diagram size: 4566 lines / 237482 characters.
PlantUML (1.2020.08) cannot parse result from dot/GraphViz.
Please go to http://plantuml.com/graphviz-dot to check your GraphViz version.
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 13.0.2+8
Operating System: Linux
Default Encoding: UTF-8
Language: en
Country: US
Machine: vmi338322.contaboserver.net
PLANTUML_LIMIT_SIZE: 4096
Processors: 6
Max Memory: 536,870,912
Total Memory: 536,870,912
Free Memory: 96,441,864
Used Memory: 440,429,048
Thread Active Count: 2
This may be caused by :
- a bug in PlantUML
- a problem in GraphViz
You should send this diagram and this image to
plantuml@gmail.com
or
post to
http://plantuml.com/qa
to solve this issue.
You can try to turn arround this issue by simplifing your diagram.
java.lang.IllegalStateException: Timeout4 TIMEOUT
net.sourceforge.plantuml.svek.DotStringFactory.getSvg(DotStringFactory.java:303)
net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:407)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:102)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:646)
net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:188)
net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:153)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:125)
nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:172)
nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:132)
java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:555)
jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:399)
jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:345)
jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
```

**Comment by sjoerdtalsma** [comment] 2020-05-06 15:46
That confirms my suspicion that your problem is actually caused by an issue in PlantUML itself, not as much in the Javadoc doclet code.
You should probably report this issue at PlantUML as well as they can resolve the real issue.
All I can do is work around it by trying an older version of PlantUML that does not have your particular issue.

You can run with the `-createPumlFiles` option to generate the PlantUML diagram sources as .puml files they will need to diagnose your issue.

**Comment by sjoerdtalsma** [comment] 2020-05-06 18:43
I now understand why your Diagrams are still generated; the printed call stack includes the following call: `net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:373)`.
This method _catches_ and prints `IllegalStateException`, which is generally a very bad idea:
```java
			} catch (IllegalStateException e) {
				e.printStackTrace();
			}
```

Which is why PlantUML continues generating diagrams, and your console gets polluted.

**Comment by sjoerdtalsma** [comment] 2020-05-06 21:36
Perhaps our issue is related to the same refactoring that caused https://forum.plantuml.net/10664/encountering-java-lang-illegalargumentexception ?

**Comment by sjoerdtalsma** [comment] 2020-05-12 11:49
_Update:_ I did regression tests with PlantUML versions all the way back to `1.2019.10` but the issue still occurs, so probably there is something in the generated `.puml` diagrams that is causing PlantUML to throw up when generating the diagrams themselves.

**Comment by bobjacobsen** [comment] 2020-06-05 04:41
I've finally been able to pin this down to a couple of .puml files. I've attached a .zipped one 
[package-dependencies.puml.zip](https://github.com/talsma-ict/umldoclet/files/4733933/package-dependencies.puml.zip)  

I created a bug report on the plantuml site, hopefully that's the right place:

https://forum.plantuml.net/11659/bug-timeout-in-large-diagram-from-doclet

**Comment by sjoerdtalsma** [comment] 2020-06-09 15:45
Thanks for reporting this; I think you may have several issues; the _large-diagram-timeout_ issue that you have reported is one of them.
The `IllegalStateException` however may very well be functional in nature and not due to a timeout, as I can reproduce it with even a very small diagram.

I reported that issue as well: https://github.com/plantuml/plantuml/issues/337

**Comment by bobjacobsen** [comment] 2020-06-09 21:40
With plantuml.jar v1.2019.8 at the front of the classpath, I've got this running without so many `IllegalStateException`. There's still one which I think is due to the size of the main diagram:
```
  [javadoc] javadoc: warning - Cannot read package list: "https://javadoc.io/static/com.github.spotbugs/spotbugs-annotations/3.1.7/package-list".
  [javadoc] javadoc: warning - Cannot read package list: "https://javadoc.io/doc/com.google.code.findbugs/jsr305/3.0.1/package-list".
  [javadoc] java.lang.IllegalStateException: Timeout4 TIMEOUT
  [javadoc] 	at net.sourceforge.plantuml.svek.DotStringFactory.getSvg(DotStringFactory.java:307)
  [javadoc] 	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:199)
  [javadoc] 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:105)
  [javadoc] 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:71)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:385)
  [javadoc] 	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:199)
  [javadoc] 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:202)
  [javadoc] 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
  [javadoc] 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
  [javadoc] 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:126)
  [javadoc] 	at nl.talsmasoftware.umldoclet.uml.Diagram.renderDiagramFile(Diagram.java:172)
  [javadoc] 	at nl.talsmasoftware.umldoclet.uml.Diagram.render(Diagram.java:132)
  [javadoc] 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
  [javadoc] 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
  [javadoc] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
  [javadoc] 	at nl.talsmasoftware.umldoclet.UMLDoclet.run(UMLDoclet.java:130)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:582)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:431)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
  [javadoc] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
  [javadoc] TimeoutExecutorB java.lang.InterruptedException
  [javadoc] java.lang.InterruptedException
  [javadoc] 	at java.base/java.lang.Object.wait(Native Method)
  [javadoc] 	at java.base/java.lang.Object.wait(Object.java:328)
  [javadoc] 	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.joinInternal(ProcessRunner.java:202)
  [javadoc] 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:125)
  [javadoc] 	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
```
The SVG output from there has more information:  
[package-dependencies.svg.zip](https://github.com/talsma-ict/umldoclet/files/4755009/package-dependencies.svg.zip)

**Comment by bobjacobsen** [comment] 2020-06-11 13:22
The beta version of PlantUML posted by @arnaudroques in https://github.com/plantuml/plantuml/issues/337#issuecomment-642288664 seems to fixe this if I put it at the front of the class path.

**Comment by sjoerdtalsma** [comment] 2020-06-11 13:29
Good! That gives us chance to release a new UmlDoclet as soon as the new beta is released.
In the mean time I'll look into the possibility of passing a timeout option from the doclet 🤞..

**Comment by sjoerdtalsma** [comment] 2020-06-11 18:59
I think I can call `OptionFlags.getInstance().setTimeoutMs(1800000L)` for the equivalent of the `-timeout 1800` commandline option.

**Comment by sjoerdtalsma** [comment] 2020-06-11 19:35
@bobjacobsen I created pull request to support the timeout option of plantuml through the doclet options, see #275

**Comment by sjoerdtalsma** [comment] 2020-06-14 12:53
@bobjacobsen I merged some branches into develop, could you try the last snapshot version to check whether the issue still exists? https://oss.sonatype.org/content/repositories/snapshots/nl/talsmasoftware/umldoclet/2.0.10-SNAPSHOT/
(please provide `--uml-timeout` option with value `1800` to try the increased timeout setting)

**Closed** 2020-06-23 19:12 UTC
Labels: bug

**Comment by bobjacobsen** [comment] 2020-07-01 03:49
Thank you for all your help, this is working well now.

**Comment by sjoerdtalsma** [comment] 2020-07-01 08:56
> Thank you for all your help, this is working well now.

Glad to hear!
