### ISSUE TITLE
Override option for SVG Object Tags

### ISSUE THREAD

**Issue by sgparry** [talsma-ict/umldoclet#410] opened 2022-05-02 20:14 UTC
**Is your feature request related to a problem? Please describe.**  
When you generate docs containing SVG, it wraps them in an object tag. If the page is then loaded into something like Word, it cannot see the SVGs.

**Describe the solution you'd like**  
An option to use img rather than object for SVGs

**Describe alternatives you've considered**  
I have post-replaced the tags in an editor. This was laborious but did work.

**Additional context**

**Comment by sjoerdtalsma** [comment] 2022-05-03 18:38
Have you tried the option `-umlImageFormat PNG`?
This should generate regular images in PNG format which will be included in normal html _img_ tags.

The .svg diagrams are embedded as html _object_ to have their hypertext links working as intended. Using the svg as _img_ in HTML would disable their links. Linking is quite useful for _hypertext_ markup documents in my opinion so I'm not a big fan of disabling that.

**Comment by sgparry** [comment] 2022-05-04 06:25
PNGs are not suitable because they are not scalable. When we import the 
docs into Word for documentation purposes, the SVGs are no longer visible. 
If they are replaced with imgs, they appear fine. I am advocating a command line option to override the behaviour. 

On 3 May 2022 19:38:18 BST, Sjoerd Talsma ***@***.***> wrote:
>Have you tried the option `-umlImageFormat PNG`?
>This should generate regular images in PNG format which will be included in normal html _img_ tags.
>
>The .svg diagrams are embedded as html _object_ to have their hypertext links working as intended. Using the svg as _img_ in HTML would disable their links. Linking is quite useful for _hypertext_ markup documents in my opinion so I'm not a big fan of disabling that.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/talsma-ict/umldoclet/issues/410#issuecomment-1116432342
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjoerdtalsma** [comment] 2022-05-05 15:10
Would you have a problem if I took a shortcut and implemented this by adding an additional option to `-umlImageFormat` like _SVG_IMG_ or something similar?
That would have little to no impact on the configuration complexity while offering you the non-default option to render SVG images with an _img_ tag instead of _object_.

**Comment by sgparry** [comment] 2022-05-05 19:15
That would be fine yes, thank you

On 5 May 2022 16:10:30 BST, Sjoerd Talsma ***@***.***> wrote:
>Would you have a problem if I took a shortcut and implemented this by adding an additional option to `-umlImageFormat` like _SVG_IMG_ or something similar?
>That would have little to no impact on the configuration complexity while offering you the non-default option to render SVG images with an _img_ tag instead of _object_.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/talsma-ict/umldoclet/issues/410#issuecomment-1118675029
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjoerdtalsma** [comment] 2022-05-05 19:52
I still need to add tests and documentation for the new `SVG_IMG` option, but could you try the latest `2.0.17-SNAPSHOT` version in the mean time to see if it meets your demands?

**Closed** 2022-05-06 13:19 UTC
